function makeTradeDeck()
%MAKETRADEDECK Generate the trade-study briefing deck (PowerPoint).
%   One slide per explainer card (docs/explainers/), plus a title slide,
%   one schematic slide per variant, and a recommendation slide. Built
%   with MATLAB Report Generator so the deck regenerates from the repo:
%   figures come from docs/figures, numbers mirror the current analysis
%   outputs. Output: docs/deliverables/GalacticSoupTradeDeck.pptx.

import mlreportgen.ppt.*
proj = currentProject;
figDir = char(fullfile(proj.RootFolder, 'docs', 'figures'));
outFile = char(fullfile(proj.RootFolder, 'docs', 'deliverables', 'GalacticSoupTradeDeck.pptx'));
if isfile(outFile), delete(outFile); end

p = Presentation(outFile);
open(p);

% --- 1: title ---
s = add(p, 'Title Slide');
replace(s, 'Title', 'Intergalactic Vegan Soup Factory');
replace(s, 'Subtitle', ['Architecture trade study at behavioral fidelity' newline ...
    'Three variants, one winner - every number reproducible with runFullAnalysis']);

% --- 2-4: the contenders (schematics carry their own stats captions) ---
variants = { ...
 'HyperCook - throughput first',  'variant_schematic_hypercook.png'; ...
 'LeanBroth - budget first',      'variant_schematic_leanbroth.png'; ...
 'EverSimmer - resilience first', 'variant_schematic_eversimmer.png'};
for i = 1:3
    s = add(p, 'Title and Content');
    replace(s, 'Title', variants{i,1});
    pic = Picture(fullfile(figDir, variants{i,2}));
    pic.Width = '11in'; pic.Height = '3.7in';
    replace(s, 'Content', pic);
end

% --- 5: static roll-up ---
s = add(p, 'Two Content');
replace(s, 'Title', '1. The paper numbers (static roll-up)');
replace(s, 'Left Content', { ...
 'Every component carries the same 11-property stereotype'; ...
 'Mass, power, cost, volume sum bottom-up through the hierarchy'; ...
 'Throughput is bottleneck math: a chain runs at its slowest stage'; ...
 'Budget caps are parsed from the requirement text at run time'; ...
 'Claims, not evidence: assumes lossless flow'});
pic = Picture(fullfile(figDir, 'budget_utilization.png'));
pic.Width = '5.6in'; pic.Height = '2.75in';
replace(s, 'Right Content', pic);

% --- 6: nominal simulation ---
s = add(p, 'Two Content');
replace(s, 'Title', '2. Run the factory (nominal simulation)');
replace(s, 'Left Content', { ...
 'Behaviors live inside the architecture models themselves'; ...
 'Batch kettles heat up physically; QC rejects a few percent and recalibrates'; ...
 'Simulated vs rated: 308 vs 320, 197 vs 210, 232 vs 240 bph'; ...
 'First bowl: 119 s continuous vs ~57 min batch cold start'; ...
 'LeanBroth''s margin is gone before the trade study even starts'});
pic = Picture(fullfile(figDir, 'behavioral_throughput.png'));
pic.Width = '5.6in'; pic.Height = '2.5in';
replace(s, 'Right Content', pic);

% --- 7: fault simulation ---
s = add(p, 'Two Content');
replace(s, 'Title', '3. Break something on purpose (worst-case fault)');
tbl = Table({ ...
 'Variant','Worst single fault','Retention'; ...
 'HyperCook','QC scanner (single string)','0%'; ...
 'LeanBroth','Prep station (single string)','0%'; ...
 'EverSimmer','One of three cells','67%'});
replace(s, 'Left Content', tbl);
pic = Picture(fullfile(figDir, 'behavioral_fault.png'));
pic.Width = '5.6in'; pic.Height = '2.5in';
replace(s, 'Right Content', pic);

% --- 8: compliance gate ---
s = add(p, 'Two Content');
replace(s, 'Title', '4. The pass/fail line (formal compliance gate)');
replace(s, 'Left Content', { ...
 'Eight quantitative requirements as executable Requirements Table rows'; ...
 'Simulated metrics feed the gate; a parallel hand-coded check must agree'; ...
 'Fail any gate and you are excluded from scoring, not ranked lower'; ...
 'An eliminated variant is a finding with a recovery path'});
tbl = Table({ ...
 'Result',''; ...
 'Checks passing','23 of 24'; ...
 'The failure','LeanBroth throughput: 196.8 vs 200 bph floor'; ...
 'Why','3% QC reject + calibration downtime ate the rated margin'; ...
 'Recovery','QC bench with reject <= ~1.3% restores compliance'});
replace(s, 'Right Content', tbl);

% --- 9: trade scoring ---
s = add(p, 'Two Content');
replace(s, 'Title', '5. Pick a winner you can defend (MCDA + Monte Carlo)');
tbl = Table({ ...
 'Scenario','EverSimmer','HyperCook'; ...
 'Balanced','0.80','0.20'; ...
 'ThroughputFirst','0.65','0.35'; ...
 'CostLean','0.90','0.10'; ...
 'MissionAssurance','0.90','0.10'});
replace(s, 'Left Content', tbl);
pic = Picture(fullfile(figDir, 'mc_winshare.png'));
pic.Width = '5.6in'; pic.Height = '2.3in';
replace(s, 'Right Content', pic);

% --- 10: recommendation ---
s = add(p, 'Title and Content');
replace(s, 'Title', 'Recommendation');
replace(s, 'Content', { ...
 'Adopt EverSimmer as the baseline architecture'; ...
 Paragraph('  wins all four stakeholder scenarios and 98.4% of 5,000 random weightings'); ...
 Paragraph('  only variant that keeps producing after any single fault (67% retention, Degraded mode)'); ...
 'LeanBroth is eliminated, not dead: a better QC bench puts it back over the throughput floor'; ...
 'HyperCook keeps a niche: 119-second cold start and the highest raw rate, at razor-thin budget margins'; ...
 'Every number regenerates from the repo: runFullAnalysis, seeded Monte Carlo, 21 unit tests, 12 project checks'});

close(p);
fprintf('deck written: %s\n', outFile);
end
